Add linting to jenkins/run-unittests, since we don't run pytests

diff --git a/jenkins/run-unittests b/jenkins/run-unittests
--- a/jenkins/run-unittests
+++ b/jenkins/run-unittests
@@ -5,6 +5,20 @@ progdir="$(realpath -e $(dirname "${0}")/..)"
 
 source $(dirname "${0}")/python-setup.sh
 
+printf -- "black --check ...\n"
+black --check .
+black_sts=${?}
+if [[ ${black_sts} -ne 0 ]]; then
+    printf -- "FAILED: black --check .\n" >&2
+fi
+printf -- "\nflake8 --verbose ...\n"
+flake8 --verbose .
+flake_sts=${?}
+if [[ ${flake_sts} -ne 0 ]]; then
+    printf -- "FAILED: flake8 --verbose .\n" >&2
+fi
+printf -- "\n"
+
 export PBENCH_UNITTEST_SERVER_MODE=parallel
 
 # List of environments to run.
